name: Cypress Tests
on: 
  push:
    brahces: [ master ]
jobs:
  application-build:
    runs-on: ubuntu-16.04
    steps:
  application-test:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Tests
        run: npm install
      - name: Run Cypress
        run: npm run cytest
        
