name: Cypress Tests
on: 
  push:
    branches: [ master ]
jobs:
  application-test:
    runs-on: ubuntu-16.04
    container: cypress/browsers:node12.16.2-chrome81-ff75
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Tests
        run: npm install
      - name: Run Cypress
        run: npm run test:chrome
        continue-on-error: true

      - name: Copy test execution videos
        run: |
          mkdir public
          cp -r cypress/videos public/videos
      
      - name: Sleep for 10 seconds
          uses: jakejarvis/wait-action@master
          with:
            time: '10s'    

      - name: Merge test results into one
        run: npm run report:merge

      - name: Generate HTML report
        run: npm run report:generate    

      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: 'AndyFever'
          user_email: 'andy.fever@gmail.com'
        