name: Cypress Tests
on: 
  push:
    branches: [ master ]
jobs:
  application-test:
    runs-on: ubuntu-16.04
    container: cypress/browsers:node12.16.2-chrome81-ff75
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Tests
        run: npm install
      - name: Run Cypress
        run: npm run test:chrome
        continue-on-error: true