name: Cypress Tests
on: [push]
jobs:
  application-build:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@AndyFever/cypress_todo
      - name: Application Build
        run: npm install
      - name: Application Run
        run: npm run start
  application-test:
    runs-on: ubuntu-16.04
    steps:
      - name: Run Cypress
        run: npm run cytests
