name: Cypress Tests
on: 
  push:
    brahces: [ master ]
jobs:
  application-build:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Application Build
        run: npm install
      - name: Application Run
        run: npm run start
  application-test:
    runs-on: ubuntu-16.04
    steps:
      - name: Sleep for 120 seconds
        uses: jakejarvis/wait-action@master
        with: 
          time: '120s'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Cypress
        run: npm run cytests
        
